# List

<h2>Soal 1: Sifat List</h2>

Jawab Pertanyaan di bawah ini:

Jenis data apa saja yang bisa ada di dalam List?

numerik, string, boolean

<h2>Soal 2: Akses List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [2]:
a = ['1', '13b', 'aa1', 1.32, 22.1, 2.34]
# slicing list
print(a[1:5])

['13b', 'aa1', 1.32, 22.1]


Expected Output :

[ '13b', 'aa1', 1.32, 22.1 ]

<h2>Soal 3: Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [4]:
# membuat list
suhu_keluarga_ucup = [
                'ayah ucup', 19, 'ucup', 19, 'ibu ucup', 20
                ]
suhu_keluarga_boy = [
                'istri boy', 20, 'anak boy', 18, 'istri kedua boy', 21
                ]

# membuat list dalam list dan di campur dengan data boolean
suhu_keluarga = [
                suhu_keluarga_ucup, suhu_keluarga_boy 
                ]
print(suhu_keluarga)

[['ayah ucup', 19, 'ucup', 19, 'ibu ucup', 20], ['istri boy', 20, 'anak boy', 18, 'istri kedua boy', 21]]


In [6]:
a = [1.32, 22.1, 2.34]
b = ['1', '13b', 'aa1']
c = [3, 40, 100]
# combine list
d = [a,c,b ]
print(d)

[[1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1']]


Expected Output :

[ [1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1'] ]

<h2>Soal 4: Akses Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [16]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# subsetting list
# print(a)
print([a[1][1],a[1][2]])

[0, 6]


Expected Output :


[0, 6]

<h2>Soal 5: Built in Function List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [19]:
p = [0, 5, 2, 10, 4, 9]
# ordered list
print(sorted(p, reverse=False))
# get max value of list
print(max(p))

[0, 2, 4, 5, 9, 10]
10


Expected Output :

[0, 2, 4, 5, 9, 10]

10

<h2>Soal 6: List Operation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [22]:
list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]

list3 = list1 + list2
print(list3)

['a', 'b', 'c', 1, 2, 3]


In [24]:
a = [1, 3, 5]
b = [5, 1, 3]
# combine list
print(b+a)

[5, 1, 3, 1, 3, 5]


Expected Output :

[5, 1, 3, 1, 3, 5]

<h2>Soal 7: List Manipulation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [44]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# change list value
#suhu_keluarga_ucup[3] = 22
#print(a[0][0:3])
a[0][0:3] = [5,9,10]
#print(a)
# change list value
#print(a[1][0:3])
a[1][0:3] = [11,0,6]
print(a)

[[5, 9, 10], [11, 0, 6]]


Expected Output :

[ [5, 9, 10], [11, 0, 6] ]

<h2>Soal 8: Delete Element List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [50]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Hilangkan elemen yang bernilai "bathroom" dan 10.50 dalam satu statement code
del areas[8:10]
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'poolhouse', 24.5, 'garage', 15.45]


Expected Output:

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'poolhouse',
 24.5,
 'garage',
 15.45]



## Soal 9: List Comprehension

Gunakan metode **list comprehension** untuk mencari anggota dari S yang habis di bagi 2, kemudian assign hasilnya dalam bentuk list ke dalam variabel T.

In [51]:
number_list = [ x for x in range(20) if x % 2 == 0]
print(number_list)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [56]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_no = []
for i in numbers:
    if i%2 == 0:
        even_no.append(i)
print(even_no)

[2, 4, 6, 8, 10]


In [57]:
S = [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
T = []
for i in S:
    if i%2 == 0:
        T.append(i)
print(T)

[0, 4, 16, 36, 64]


Expected Output:

[0, 4, 16, 36, 64]

# Dictionary

<h2>Soal 10: Akses Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [63]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# print semua key yang ada di objek europe
print(europe.keys())
# print nilai dari key franche
print(europe['france'])

dict_keys(['spain', 'france', 'germany', 'norway'])
paris


Expected Output:

dict_keys(['spain', 'france', 'germany', 'norway'])

paris

<h2>Soal 11: Menambahkan key-value baru ke Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [64]:
# dictionary awal
student = {
  "nama" : "faqih",
  "umur" : 26,
  "tinggi" : 177.6
}

#cetak dictionary
print(student)

#tambah key dan value 
student["hobi"] = "coding"

#cetak dictionary
print(student)

{'nama': 'faqih', 'umur': 26, 'tinggi': 177.6}
{'nama': 'faqih', 'umur': 26, 'tinggi': 177.6, 'hobi': 'coding'}


In [69]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# tambahkan key itali ke objek dictionary dengan value roma
europe["itali"] = "roma"
#print(europe)
# cek apakah itali ada di dalam objek dictionary
print('itali' in europe)

True


Expected Output:
    
True

<h2>Soal 12: Update dan Remove Dictinary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [77]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }

# update nilai ibukota german ke berlin
#print(europe)
europe["germany"]="berlin"

# remove australia dari europa
europe.pop("australia")
print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}


Expected Output:

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

<h2>Soal 13: Nested Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [82]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } 
         }

# berapa populasi dari kota german?
print(country["germany"]['population'])

# update data baru, yaitu negara indonesia dengan capital jakarta dan poulasi 250
country["indonesia"] = {'capital': 'jakarta', 'poulasi': 250}

print(country)

80.62
{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'poulasi': 250}}


Expected Output:

80.62

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}

<h2>Soal 14: Loop Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [86]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 },
           'indonesia' : {'capital':'jakarta', 'population':250}
         }

for ct in country :
    print('Ibukota '+ ct +' adalah '+country[ct]['capital'])

Ibukota spain adalah madrid
Ibukota france adalah paris
Ibukota germany adalah berlin
Ibukota norway adalah oslo
Ibukota indonesia adalah jakarta


Expected Output:
    
Ibukota spain adalah madrid

Ibukota france adalah paris

Ibukota germany adalah berlin

Ibukota norway adalah oslo

Ibukota indonesia adalah jakarta

<h2>Tugas Tambahan</h2>
1. Remove Duplicate List

In [11]:
# solusi tanpa menggunakan set
new_list = []
dup = set()
uniq = []
def remove_duplicate(obj_list):
    for i in obj_list :
        if i not in new_list :
            new_list.append(i)
    return new_list

# solusi dengan menggunakan set
def remove_duplicate_with_set(obj_list):
    for i in obj_list :
        if i not in dup :
            uniq.append(i)
            dup.add(i)
            new_list = list(dup)
    return new_list

obj_list = [1, 2, 4, 6, 2, 1, 4, 5, 7, 8, 6]
print(remove_duplicate(obj_list))
print(remove_duplicate_with_set(obj_list))

#output :
#[1, 2, 4, 6, 5, 7, 8]
#[1, 2, 4, 5, 6, 7, 8]

[1, 2, 4, 6, 5, 7, 8]
[1, 2, 4, 5, 6, 7, 8]


2. Membuat ChatBot Sederhana

In [30]:
# import library
from datetime import datetime
import random

# ganti dengan sebuah nama
nama  = "Arif Zainurrohman"
# variabel tanggal
tanggal = datetime.now().day
# default variabel untuk pertanyaan tidak diketahui
default = "maaf, aku tidak tahu jawaban dari pertanyaanmu"

# Membuat objek dictionary berisi berbagai opsi jawaban

# list jawaban untuk pertanyaan tentang nama
jawaban_nama = [
      "nama saya  {0}".format(nama),
      "orang-orang memanggil saya {0}".format(nama),
      "panggil saja saya {0}".format(nama)
   ]

# list jawaban untuk pertanyaan tentang tanggal
jawaban_tanggal = [
      "hari ini tanggal {0}".format(tanggal),
      "ya ampun masa tidak tahu, hari ini tanggal".format(tanggal)
    ]

# opsi pertanyaan yang bisa dijawab
pertanyaan = {
  "nama kamu siapa?": jawaban_nama,
  "kamu siapa?" : jawaban_nama,
  "tanggal berapa hari ini?": jawaban_tanggal,
  "hari ini tanggal berapa?" : jawaban_tanggal,
  "default": default
}

# list jawaban untuk sebuah argument selain pertanyaan
statement =  [
                  'ceritakan lebih banyak!',
                  'kenapa kamu berpikir begitu?',
                  'sudah berapa lama kamu merasa seperti ini?',
                  'Itu sangat menarik!',
                  'oh wow!',
                  ':)'
              ]

# respon keseluruhan
responses = {
    'pertanyaan' : pertanyaan,
    'statement' : statement
}
#------
             
# ayo buat chatbotmu
def chatbot(message):
    if message == "Selamat pagi" :
        random.choice['statement']        
    elif message in pertanyaan :
        responses['pertanyaan'] = message;
        responses['statement'] = random.choice(pertanyaan[message])
    else :
        responses['pertanyaan'] = message;
        responses['statement'] = pertanyaan['default']
    return responses['statement']
    
print(chatbot('Selamat Pagi'))
print(chatbot('Mau bermain bersamaku?'))
print(chatbot('nama kamu siapa?'))
print(chatbot('hari ini tanggal berapa?'))

#output :
#:)
#maaf, aku tidak tahu jawaban dari pertanyaanmu
#orang-orang memanggil saya Nama Anda
#ya ampun masa tidak tahu, hari ini tanggal

maaf, aku tidak tahu jawaban dari pertanyaanmu
maaf, aku tidak tahu jawaban dari pertanyaanmu
orang-orang memanggil saya Arif Zainurrohman
ya ampun masa tidak tahu, hari ini tanggal
